apiVersion: apiconnect.ibm.com/v1beta1
kind: APIConnectCluster
metadata:
  annotations:
    apiconnect-operator/backups-not-configured: 'true'
    apiconnect-operator/cp4i: 'false'
  name: apim-demo
  labels:
    app.kubernetes.io/instance: apiconnect
    app.kubernetes.io/managed-by: ibm-apiconnect
    app.kubernetes.io/name: apiconnect-small
  namespace: apic
spec:
  license:
    accept: true
    license: L-DZZQ-MGVN8V
    metric: VIRTUAL_PROCESSOR_CORE
    use: nonproduction
  analytics:
    storage:
      enabled: true
      type: shared
    mtlsValidateClient: true
  portal:
    mtlsValidateClient: true
  profile: n1xc16.m72
  storageClassName: ibmc-block-gold
  version: 10.0.8.1
