apiVersion: appconnect.ibm.com/v1beta1
kind: IntegrationRuntime
metadata:
  name: jgr-mqreqresp-backend
spec:
  license:
    accept: true
    license: L-KPRV-AUG9NC
    use: CloudPakForIntegrationNonProduction
  template:
    spec:
      containers:
        - name: runtime
          resources:
            limits:
              cpu: 1
              memory: 1Gi
            requests:
              cpu: 1
              memory: 1Gi
  replicas: 1
  version: '13.0'
  barURL: 
    - >-
      https://github.com/gomezrjo/cp4idemo/raw/main/barfiles/MQBackend.bar
  configurations:
    - github-barauth
    - ace-qmgr-demo-policy
    - jgr-default-qmgr