apiVersion: eventstreams.ibm.com/v1beta2
kind: EventStreams
metadata:
  name: es-demo
  namespace: tools
  labels:
    backup.eventstreams.ibm.com/component: eventstreams
spec:
  version: latest
  license:
    accept: true
    license: L-KCVZ-JL5CRM
    use: EventAutomationNonProduction
  adminApi: {}
  adminUI:
    authentication:
      - type: scram-sha-512
  apicurioRegistry: {}
  collector: {}
  requestIbmServices:
    iam: false
    monitoring: false
  restProducer: {}
  strimziOverrides:
    kafka:
      replicas: 3
      authorization:
        type: simple
      config:
        inter.broker.protocol.version: '3.9'
        log.cleaner.threads: 6
        num.io.threads: 24
        num.network.threads: 9
        num.replica.fetchers: 3
        offsets.topic.replication.factor: 3
        default.replication.factor: 3
        min.insync.replicas: 2
      listeners:
        - name: authsslsvc
          port: 9095
          type: internal
          tls: true          
          authentication:
            type: scram-sha-512
        - name: external
          port: 9094
          type: route
          tls: true
          authentication:
            type: scram-sha-512
      resources:
        requests:
          memory: 128Mi
          cpu: 100m
        limits:
          memory: 2048Mi
          cpu: 1000m
      storage:
        type: persistent-claim
        size: 4Gi
        class: ocs-storagecluster-ceph-rbd
    zookeeper:
      replicas: 3
      storage:
        type: persistent-claim
        size: 2Gi
        class: ocs-storagecluster-ceph-rbd
    entityOperator:
      topicOperator: {}
      userOperator: {}