apiVersion: sources.knative.dev/v1beta1
kind: KafkaSource
metadata:
  name: geocodetopicsource
spec:
  bootstrapServers:
  - ${ES_BOOTSTRAP_SERVER}
  sink:
    ref:
      apiVersion: serving.knative.dev/v1
      kind: Service
      name: surveyadminservice
    uri: "/api/cloudevents/geocodeComplete"
  topics:
  - geocodetopic