apiVersion: sources.knative.dev/v1beta1
kind: KafkaSource
metadata:
  name: locationtopicsource
spec:
  bootstrapServers:
  - ${ES_BOOTSTRAP_SERVER}
  sink:
    ref:
      apiVersion: serving.knative.dev/v1
      kind: Service
      name: surveygeocoderservice
    uri: "/api/cloudevents/locationInput"
  topics:
  - locationtopic