apiVersion: operator.serverless.openshift.io/v1alpha1
kind: KnativeKafka
metadata:
    name: knative-kafka
    namespace: knative-eventing
spec:
    channel:
        enabled: true 
        bootstrapServers: ${ES_BOOTSTRAP_SERVER}
        authSecretName: knative-es-demo-auth
        authSecretNamespace: knative-eventing
    source:
        enabled: true 
    broker:
        enabled: true 
        defaultConfig:
            bootstrapServers: ${ES_BOOTSTRAP_SERVER}
            numPartitions: 10
            replicationFactor: 3
            authSecretName: knative-es-demo-auth
    sink:
        enabled: true 
    logging:
        level: INFO 