apiVersion: v1
kind: Secret
metadata:
  name: apim-credentials-user-pwd
type: Opaque
stringData:
  base_url: ${APIC_BASE_URL}
  username: ${APIC_USER_NAME}
  password: ${APIC_USER_PWD}
  disable_trust: 'true'
  trusted_cert: |-
${APIC_TRUSTED_CERT}