apiVersion: mq.ibm.com/v1beta1
kind: QueueManager
metadata:
  annotations:
    com.ibm.mq/write-defaults-spec: 'false'
  name: qmgr-multi-block
spec:
  annotations:
    productName: "IBM MQ Advanced Container Multi Instance for Non-Production Environments with CP4I License"
    productID: "31f844f7a96b49749130cd0708fdbb17"
    productChargedContainers: "All"
    productMetric: "VIRTUAL_PROCESSOR_CORE"
    productCloudpakRatio: "10:3"
    cloudpakName: "IBM Cloud Pak for Integration"
    cloudpakId: "c8b82d189e7545f0892db9ef2731b90d"
  license:
    accept: true
    license: L-JTPV-KYG8TF
    use: NonProduction
  queueManager:
    name: QMGRMULTI
    resources:
      limits:
        cpu: 500m
      requests:
        cpu: 500m
    storage:
      queueManager:
        type: persistent-claim
        class: ocs-storagecluster-ceph-rbd
      persistedData:
        enabled: true
        class: ocs-storagecluster-cephfs
        type: persistent-claim
      recoveryLogs:
        enabled: true
        class: ocs-storagecluster-cephfs
        type: persistent-claim
    availability:
      type: MultiInstance
  template:
    pod:
      containers:
        - env:
            - name: MQSNOAUT
              value: 'yes'
          name: qmgr
  version: 9.4.0.11-r2
  web:
    console:
      authentication:
        provider: integration-keycloak
      authorization:
        provider: integration-keycloak
    enabled: true
  securityContext:
    supplementalGroups:
      - 65534