apiVersion: mq.ibm.com/v1beta1
kind: QueueManager
metadata:
  annotations:
    com.ibm.mq/write-defaults-spec: 'false'
  name: qmgr-bake-image
spec:
  license:
    accept: true
    license: L-JTPV-KYG8TF
    use: NonProduction
  queueManager:
    image: quay.io/jgomezr/mq-image-9.4.0.10-r1-jgrcp4i:1.0.0
    name: QMGRBAKEIMG
    resources:
      limits:
        cpu: 500m
      requests:
        cpu: 500m
    storage:
      queueManager:
        type: persistent-claim
      defaultClass: ocs-storagecluster-ceph-rbd
      defaultDeleteClaim: true
    availability:
      type: SingleInstance
    logFormat: JSON
  version: 9.4.0.11-r2
  web:
    console:
      authentication:
        provider: integration-keycloak
      authorization:
        provider: integration-keycloak
    enabled: true