apiVersion: events.ibm.com/v1beta1
kind: EventProcessing
metadata:
  name: ep-demo
  namespace: tools
spec:
  license:
    accept: true
    license: L-KCVZ-JL5CRM
    use: EventAutomationNonProduction
  flink:
    endpoint: 'ea-flink-demo-rest:8081'
  authoring:
    authConfig:
      authType: OIDC
      oidcConfig:
        authorizationClaimPointer: /effectiveRoles
        clientIDKey: CLIENT_ID
        clientSecretKey: CLIENT_SECRET
        discovery: true
        secretName: keycloak-client-secret-ep-demo-ibm-ep-keycloak
        site: 'https://cpfs-opcon-cs-keycloak-service.ibm-common-services.svc:8443/realms/cloudpak/'
    storage:
      storageClassName: ocs-storagecluster-ceph-rbd
      type: persistent-claim
      size: 100M
    template:
      pod:
        spec:
          containers:
            - name: backend
              env:
                - name: JAVA_TOOL_OPTIONS
                  value: '-Djavax.net.ssl.trustStore=/opt/ibm/sp-backend/certs/eventautomation.jks -Djavax.net.ssl.trustStorePassword=eventautomationstore'
                - name: EI_AUTH_VALIDATE_DISCOVERY_ISSUER
                  value: 'false'
              volumeMounts:
                - mountPath: /opt/ibm/sp-backend/certs
                  name: truststore
          volumes:
            - name: truststore
              secret:
                items:
                  - key: eventautomation.jks
                    path: eventautomation.jks
                secretName: eventautomation-truststore
    tls:
      trustedCertificates:
        - certificate: ca.crt
          secretName: keycloak-bindinfo-cs-keycloak-tls-secret