apiVersion: operators.coreos.com/v1alpha1
kind: CatalogSource
metadata:
  name: ibm-eventautomation-flink-catalog
  namespace: openshift-marketplace
spec:
  displayName: ibm-eventautomation-flink-1.2.0
  publisher: IBM
  image: icr.io/cpopen/ibm-eventautomation-flink-operator-catalog@sha256:e02a9f9288146c9c45b84f35d5727fcb6ba542de8769cde688f12506653fab2a
  sourceType: grpc
  updateStrategy:
    registryPoll:
      interval: 30m0s