apiVersion: operators.coreos.com/v1alpha1
kind: CatalogSource
metadata:
  name: ibm-eventprocessing-catalog
  namespace: openshift-marketplace
spec:
  displayName: ibm-eventprocessing-1.2.0
  publisher: IBM
  image: icr.io/cpopen/ibm-eventprocessing-operator-catalog@sha256:4109cca3dae62836f22db0eadc470e4716dfd2634e0d090ec733f11b549057a3
  sourceType: grpc
  updateStrategy:
    registryPoll:
      interval: 30m0s