{
 "title": "mq_qm_grafana_dashboard",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "qmgr", "label": "Queue Manager", "query": "label_values(qmgr)" }
  ]
 },
 "panels": [
  {
   "title": "Successful MQGET/MQPUT",
   "type": "singlestat",
   "description": "Number of Successful Operations",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(ibmmq_qmgr_mqput_mqput1_total{qmgr=\"$qmgr\"})+sum(ibmmq_qmgr_destructive_get_total{qmgr=\"$qmgr\"})"
    },
    {}
   ]
  },
  {
   "title": "Message Throughput",
   "type": "graph",
   "gridPos": { "h": 8, "w": 20, "x": 4, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(ibmmq_qmgr_mqput_mqput1_total{qmgr=\"$qmgr\"}[5m])",
     "legendFormat": "MQPUT"
    },
    {
     "expr": "rate(ibmmq_qmgr_destructive_get_total{qmgr=\"$qmgr\"}[5m])",
     "legendFormat": "MQGET"
    }
   ]
  },
  {
   "title": "Unsuccessful MQGET/MQPUT",
   "type": "singlestat",
   "description": "unsuccessful MQPUT transactions",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 4 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(ibmmq_qmgr_failed_mqput1_total{qmgr=\"$qmgr\"})+sum(ibmmq_qmgr_failed_mqput_total{qmgr=\"$qmgr\"})+sum(ibmmq_qmgr_failed_mqget_total{qmgr=\"$qmgr\"})"
    }
   ]
  },
  {
   "title": "Maximum CPU Load",
   "type": "singlestat",
   "description": "# Maximum CPU Load\n\nMaximum CPU Load of all Queue Managers",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 8 },
   "format": "percent",
   "valueName": "max",
   "targets": [
    {
     "expr": "max(ibmmq_qmgr_cpu_load_one_minute_average_percentage{qmgr=\"$qmgr\"})"
    }
   ]
  },
  {
   "title": "Log System Usage",
   "type": "singlestat",
   "description": "# Log Usage\n\nLog system usage of Queue Manager",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 8 },
   "format": "percent",
   "valueName": "avg",
   "targets": [
    {
     "expr": "(ibmmq_qmgr_log_file_system_in_use_bytes{qmgr=\"$qmgr\"} / ibmmq_qmgr_log_file_system_max_bytes{qmgr=\"$qmgr\"}) * 100"
    }
   ]
  },
  {
   "title": "Log Write Latency",
   "type": "singlestat",
   "description": "# Log Write Latency\n\nMaximum Log Write Latency of all Queue Managers",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 8 },
   "format": "s",
   "valueName": "current",
   "targets": [
    {
     "expr": "max(ibmmq_qmgr_log_write_latency_seconds{qmgr=\"$qmgr\"})"
    }
   ]
  },
  {
   "title": "MQ Connections",
   "type": "singlestat",
   "description": "# MQ Connections\n\nNumber of MQ Connections accross all Queue Managers",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 15 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(ibmmq_qmgr_mqconn_mqconnx_total{qmgr=\"$qmgr\"})"
    }
   ]
  },
  {
   "title": "FDC Errors",
   "type": "singlestat",
   "description": "# FDC Errors\n\nNumber of FDC files across all Queue Managers",
   "gridPos": { "h": 6, "w": 4, "x": 4, "y": 15 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(ibmmq_qmgr_fdc_files{qmgr=\"$qmgr\"})"
    }
   ]
  },
  {
   "title": "Failed Stats",
   "type": "graph",
   "gridPos": { "h": 6, "w": 16, "x": 8, "y": 15 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "sum_over_time(ibmmq_qmgr_failed_browse_total{qmgr=\"$qmgr\"}[5m]) ",
     "legendFormat": "Failed Browse"
    },
    {
     "expr": "sum_over_time(ibmmq_qmgr_failed_mqopen_total{qmgr=\"$qmgr\"}[5m])",
     "legendFormat": "Failed MQOpen"
    },
    {
     "expr": "sum_over_time(ibmmq_qmgr_failed_mqsubrq_total{qmgr=\"$qmgr\"}[5m])",
     "legendFormat": "Failed MQSUBRQ"
    },
    {
     "expr": "sum_over_time(ibmmq_qmgr_failed_mqconn_mqconnx_total{qmgr=\"$qmgr\"}[5m])",
     "legendFormat": "Failed MQCONN_MQCONNX"
    }
   ]
  }
 ]
}