apiVersion: eventstreams.ibm.com/v1beta2
kind: KafkaTopic
metadata:
  name: cp4i-ivt-topic
  namespace: tools
  labels:
    eventstreams.ibm.com/cluster: es-demo
spec:
  partitions: 1
  replicas: 3
  config:
    retention.ms: '86400000'
---
apiVersion: eventstreams.ibm.com/v1beta2
kind: KafkaTopic
metadata:
  name: cp4i-es-demo-topic
  namespace: tools
  labels:
    eventstreams.ibm.com/cluster: es-demo
spec:
  partitions: 1
  replicas: 3
  config:
    retention.ms: '86400000'
---
apiVersion: eventstreams.ibm.com/v1beta2
kind: KafkaTopic
metadata:
  name: cp4i-mq-2-es-demo-topic
  namespace: tools
  labels:
    eventstreams.ibm.com/cluster: es-demo
spec:
  partitions: 1
  replicas: 3
  config:
    retention.ms: '86400000'
---
apiVersion: eventstreams.ibm.com/v1beta2
kind: KafkaTopic
metadata:
  name: cp4i-es-2-mq-demo-topic
  namespace: tools
  labels:
    eventstreams.ibm.com/cluster: es-demo
spec:
  partitions: 1
  replicas: 3
  config:
    retention.ms: '86400000'
---
apiVersion: eventstreams.ibm.com/v1beta2
kind: KafkaTopic
metadata:
  name: fake-orders
  namespace: tools
  labels:
    eventstreams.ibm.com/cluster: es-demo
spec:
  config:
    min.insync.replicas: '1'
    retention.bytes: '1024288000'
  partitions: 3
  replicas: 3
  topicName: ORDERS.NEW
---
apiVersion: eventstreams.ibm.com/v1beta2
kind: KafkaTopic
metadata:
  name: fake-cancellations
  namespace: tools
  labels:
    eventstreams.ibm.com/cluster: es-demo
spec:
  config:
    min.insync.replicas: '1'
    retention.bytes: '1024288000'
  partitions: 3
  replicas: 3
  topicName: CANCELLATIONS
---
apiVersion: eventstreams.ibm.com/v1beta2
kind: KafkaTopic
metadata:
  name: fake-badgeevents
  namespace: tools
  labels:
    eventstreams.ibm.com/cluster: es-demo
spec:
  config:
    min.insync.replicas: '1'
    retention.bytes: '1024288000'
  partitions: 3
  replicas: 1
  topicName: DOOR.BADGEIN
---
apiVersion: eventstreams.ibm.com/v1beta2
kind: KafkaTopic
metadata:
  name: fake-stockmovement
  namespace: tools
  labels:
    eventstreams.ibm.com/cluster: es-demo
spec:
  config:
    min.insync.replicas: '1'
    retention.bytes: '1024288000'
  partitions: 3
  replicas: 1
  topicName: STOCK.MOVEMENT
---
apiVersion: eventstreams.ibm.com/v1beta2
kind: KafkaTopic
metadata:
  name: fake-customers
  namespace: tools
  labels:
    eventstreams.ibm.com/cluster: es-demo
spec:
  config:
    min.insync.replicas: '1'
    retention.bytes: '1024288000'
  partitions: 3
  replicas: 3
  topicName: CUSTOMERS.NEW
---
apiVersion: eventstreams.ibm.com/v1beta2
kind: KafkaTopic
metadata:
  name: fake-sensorreadings
  namespace: tools
  labels:
    eventstreams.ibm.com/cluster: es-demo
spec:
  config:
    min.insync.replicas: '1'
    retention.bytes: '1024288000'
  partitions: 3
  replicas: 1
  topicName: SENSOR.READINGS
---
apiVersion: eventstreams.ibm.com/v1beta2
kind: KafkaTopic
metadata:
  name: apic-analytics-offload-topic
  namespace: tools
  labels:
    eventstreams.ibm.com/cluster: es-demo
spec:
  partitions: 1
  replicas: 3
  config:
    retention.ms: '86400000'
---
apiVersion: eventstreams.ibm.com/v1beta2
kind: KafkaUser
metadata:
  labels:
    app.kubernetes.io/instance: es-demo
    eventstreams.ibm.com/cluster: es-demo
  name: ace-user
  namespace: tools
spec:
  authentication:
    type: scram-sha-512
  authorization:
    acls:
      - host: '*'
        operation: Read
        resource:
          name: '*'
          patternType: literal
          type: topic
      - host: '*'
        operation: Read
        resource:
          name: __schema_
          patternType: prefix
          type: topic
      - host: '*'
        operation: Write
        resource:
          name: '*'
          patternType: literal
          type: topic
      - host: '*'
        operation: Create
        resource:
          name: '*'
          patternType: literal
          type: topic
      - host: '*'
        operation: Alter
        resource:
          name: __schema_
          patternType: prefix
          type: topic
      - host: '*'
        operation: Read
        resource:
          name: '*'
          patternType: literal
          type: group
      - host: '*'
        operation: Write
        resource:
          name: '*'
          patternType: literal
          type: transactionalId
    type: simple
---
apiVersion: eventstreams.ibm.com/v1beta2
kind: KafkaUser
metadata:
  labels:
    app.kubernetes.io/instance: es-demo
    eventstreams.ibm.com/cluster: es-demo
  name: kafka-connect-user
  namespace: tools
spec:
  authentication:
    type: scram-sha-512
  authorization:
    acls:
      - host: '*'
        operation: Read
        resource:
          name: '*'
          patternType: literal
          type: topic
      - host: '*'
        operation: Read
        resource:
          name: __schema_
          patternType: prefix
          type: topic
      - host: '*'
        operation: Write
        resource:
          name: '*'
          patternType: literal
          type: topic
      - host: '*'
        operation: Create
        resource:
          name: '*'
          patternType: literal
          type: topic
      - host: '*'
        operation: Alter
        resource:
          name: __schema_
          patternType: prefix
          type: topic
      - host: '*'
        operation: Read
        resource:
          name: '*'
          patternType: literal
          type: group
      - host: '*'
        operation: Write
        resource:
          name: '*'
          patternType: literal
          type: transactionalId
    type: simple
---
apiVersion: eventstreams.ibm.com/v1beta2
kind: KafkaUser
metadata:
  labels:
    app.kubernetes.io/instance: es-demo
    eventstreams.ibm.com/cluster: es-demo
  name: kafka-bridge-user
  namespace: tools
spec:
  authentication:
    type: scram-sha-512
  authorization:
    acls:
      - host: '*'
        operation: Read
        resource:
          name: '*'
          patternType: literal
          type: topic
      - host: '*'
        operation: Read
        resource:
          name: __schema_
          patternType: prefix
          type: topic
      - host: '*'
        operation: Write
        resource:
          name: '*'
          patternType: literal
          type: topic
      - host: '*'
        operation: Create
        resource:
          name: '*'
          patternType: literal
          type: topic
      - host: '*'
        operation: Alter
        resource:
          name: __schema_
          patternType: prefix
          type: topic
      - host: '*'
        operation: Read
        resource:
          name: '*'
          patternType: literal
          type: group
      - host: '*'
        operation: Write
        resource:
          name: '*'
          patternType: literal
          type: transactionalId
    type: simple
---
apiVersion: eventstreams.ibm.com/v1beta2
kind: KafkaUser
metadata:
  labels:
    app.kubernetes.io/instance: es-demo
    eventstreams.ibm.com/cluster: es-demo
  name: eem-user
  namespace: tools
spec:
  authentication:
    type: scram-sha-512
  authorization:
    acls:
      - host: '*'
        operation: Read
        resource:
          name: '*'
          patternType: literal
          type: topic
      - host: '*'
        operation: Read
        resource:
          name: __schema_
          patternType: prefix
          type: topic
      - host: '*'
        operation: Write
        resource:
          name: '*'
          patternType: literal
          type: topic
      - host: '*'
        operation: Create
        resource:
          name: '*'
          patternType: literal
          type: topic
      - host: '*'
        operation: Alter
        resource:
          name: __schema_
          patternType: prefix
          type: topic
      - host: '*'
        operation: Read
        resource:
          name: '*'
          patternType: literal
          type: group
      - host: '*'
        operation: Write
        resource:
          name: '*'
          patternType: literal
          type: transactionalId
    type: simple
---
apiVersion: eventstreams.ibm.com/v1beta2
kind: KafkaUser
metadata:
  labels:
    app.kubernetes.io/instance: es-demo
    eventstreams.ibm.com/cluster: es-demo
  name: ep-user
  namespace: tools
spec:
  authentication:
    type: scram-sha-512
  authorization:
    acls:
      - host: '*'
        operation: Read
        resource:
          name: '*'
          patternType: literal
          type: topic
      - host: '*'
        operation: Read
        resource:
          name: __schema_
          patternType: prefix
          type: topic
      - host: '*'
        operation: Write
        resource:
          name: '*'
          patternType: literal
          type: topic
      - host: '*'
        operation: Create
        resource:
          name: '*'
          patternType: literal
          type: topic
      - host: '*'
        operation: Alter
        resource:
          name: __schema_
          patternType: prefix
          type: topic
      - host: '*'
        operation: Read
        resource:
          name: '*'
          patternType: literal
          type: group
      - host: '*'
        operation: Write
        resource:
          name: '*'
          patternType: literal
          type: transactionalId
    type: simple
---
apiVersion: eventstreams.ibm.com/v1beta2
kind: KafkaUser
metadata:
  labels:
    app.kubernetes.io/instance: es-demo
    eventstreams.ibm.com/cluster: es-demo
  name: apic-analytics-offload-user
  namespace: tools
spec:
  authentication:
    type: scram-sha-512
  authorization:
    acls:
      - host: '*'
        operation: Read
        resource:
          name: '*'
          patternType: literal
          type: topic
      - host: '*'
        operation: Read
        resource:
          name: __schema_
          patternType: prefix
          type: topic
      - host: '*'
        operation: Write
        resource:
          name: '*'
          patternType: literal
          type: topic
      - host: '*'
        operation: Create
        resource:
          name: '*'
          patternType: literal
          type: topic
      - host: '*'
        operation: Alter
        resource:
          name: __schema_
          patternType: prefix
          type: topic
      - host: '*'
        operation: Read
        resource:
          name: '*'
          patternType: literal
          type: group
      - host: '*'
        operation: Write
        resource:
          name: '*'
          patternType: literal
          type: transactionalId
    type: simple
---
apiVersion: eventstreams.ibm.com/v1beta2
kind: KafkaUser
metadata:
  labels:
    app.kubernetes.io/instance: es-demo
    eventstreams.ibm.com/cluster: es-demo
  name: my-user
  namespace: tools
spec:
  authentication:
    type: scram-sha-512
  authorization:
    acls:
      - host: '*'
        operations:
          - Read
          - Write
          - Create
        resource:
          name: '*'
          patternType: literal
          type: topic
      - host: '*'
        operations:
          - Read
          - Alter
        resource:
          name: __schema_
          patternType: prefix
          type: topic
      - host: '*'
        operations:
          - Read
        resource:
          name: '*'
          patternType: literal
          type: group
      - host: '*'
        operations:
          - Write
        resource:
          name: '*'
          patternType: literal
          type: transactionalId
    type: simple