kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: eventstreams-kafka-broker
  labels:
    app: eventstreams
rules:
- verbs:
      - get
      - create
      - watch
      - update
      - delete
      - list
  apiGroups:
      - rbac.authorization.k8s.io
  resources:
      - clusterrolebindings
- verbs:
      - get
      - create
      - watch
      - update
      - delete
      - list
  apiGroups:
      - ""
  resources:
      - nodes