apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: ace-is-hpa-demo
spec:
  scaleTargetRef:
    kind: IntegrationServer
    name: jgr-ace-ivt-bake
    apiVersion: appconnect.ibm.com/v1beta1
  minReplicas: 2
  maxReplicas: 5
  targetCPUUtilizationPercentage: 10