apiVersion: keda.sh/v1alpha1
kind: TriggerAuthentication
metadata:
  name: ace-keda-trigger
spec:
  secretTargetRef:
    - parameter: username
      name: keda-mq-secret
      key: ADMIN_USER
    - parameter: password
      name: keda-mq-secret
      key: ADMIN_PASSWORD
    - parameter: cert
      name: keda-mq-secret
      key: cert
    - parameter: key
      name: keda-mq-secret
      key: key