apiVersion: appconnect.ibm.com/v1beta1
kind: IntegrationRuntime
metadata:
  name: jgr-customer-db
  namespace: tools
spec:
  license:
    accept: true
    license: L-XRNH-47FJAW
    use: CloudPakForIntegrationNonProduction
  template:
    spec:
      containers:
        - name: runtime
          resources:
            limits:
              cpu: 500m
              memory: 512Mi
            requests:
              cpu: 500m
              memory: 512Mi
  replicas: 1
  version: '12.0'
  barURL: 
    - https://github.com/gomezrjo/cp4idemo/raw/main/barfiles/CustomerDB.bar
  configurations:
    - github-barauth